### ISSUE TITLE
es6 configuration

### ISSUE THREAD

**Issue by vmariano** [seykron/ogov-importer#20]
Witch version of node vm?

Some special config?

thanks.

**Comment by seykron** [comment]
No special config. It requires node >= 0.10 in master and develop, and node 4 in branch **feature/refactor-es6** since it uses ES6.

It uses [debug](https://github.com/visionmedia/debug) in order to log information to the console. It reads the DEBUG environment variable to enable specific loggers. My DEBUG variable looks like this:

```
export DEBUG=importer,bill_importer,people_importer,committee_importer
```

**Comment by vmariano** [comment]
:+1:

**Comment by seykron** [comment]
you have it working already :P

**Comment by vmariano** [comment]
yes, sorry.
